### ISSUE TITLE
jni/Jgles2_*.h files are missing

### ISSUE THREAD

**Issue by r0k** [chriscamacho/Jgles2pi#1]
It seems that the header files for the java native elements are missing - **Jgles2_util.h**, **Jgles2_EGL.h** and **Jgles2_GLES2.h**. C files are using them as include and the Makefile references them too.

``` makefile
jni/util.o: jni/util.c jni/Jgles2_util.h
    $(CC) $(CFLAGS) -c $< -o $@

jni/egl.o: jni/egl.c jni/Jgles2_EGL.h
    $(CC) $(CFLAGS) -c $< -o $@

jni/gles2.o: jni/gles2.c jni/Jgles2_GLES2.h
    $(CC) $(CFLAGS) -c $< -o $@
```

**Comment by chriscamacho** [comment]
These files are autogenerated by javah, just run ant without properties and the whole thing should build and run the test...
Feel free to contact me via the contact form on bedroomcoders.co.uk if you're struggling...
